### ISSUE TITLE
Cant handle ajax source

### ISSUE THREAD

**Issue by fr0z3nfyr** [reside-ic/TreeTables#13]
doesn't work if there's no `data` option specified in the DT options and instead `ajaxSource` or `ajax.url` is used. Most of the times in real world, data tables is used with ajax data.

**Comment by hillalex** [comment]
At the moment we don't have plans to support ajax data because it's not needed for our projects, but I'd be happy to review a pull request if you wanted to submit one.

**Comment by fr0z3nfyr** [comment]
I will try to incorporate the feature and send a PR. It might take some time but I will definitely do it.
