### ISSUE TITLE
Selecting Row & Information

### ISSUE THREAD

**Issue by scott-oliver** [reside-ic/TreeTables#6]
Firstly, I'd like to say thank you for such a wonderful addition to data tables, this is exactly what I have been searching for!

I'd like to point you to a SO question I have raised regarding your plugin, hopefully this can not only provide me with answer to some information, but highlight your plugin too!

https://stackoverflow.com/questions/56488109/select-datatable-row-in-tree-table-plugin

This certainly isn't an "issue", but I'm struggling to execute a few of the data table functions using this plugin, hopefully you can point me in the right direction.

I need to select the row and trigger an event (in this example, providing an alert with the row's name and salary values). I need this to happen independently to expanding and collapsing the row, meaning that these are two seperate triggers (expanding and collapsing from the icon, and selecting the row from the rows contents).

Hope you can help me out!

**Comment by hillalex** [comment]
Hi Scott, thanks for the feedback, I'm so happy you found it useful!

Actually the default behaviour here overrides the ability to select a row without triggering the expand/collapse event, I had overlooked that.

I think this is an "issue" and I'm happy to change the default behaviour to toggle rows only when clicking the icon. Will open a PR to fix this in the next day or so, thanks for pointing this out!
